FROM_SESSION = DropboxSession.new(ENV["DROPBOX_APP_KEY"], ENV["DROPBOX_APP_KEY_SECRET"])
FROM_SESSION.set_access_token(*[ENV["DROPBOX_FIRST_KEY"],ENV["DROPBOX_SECOND_KEY"]])
FROM_CLIENT = DropboxClient.new(FROM_SESSION, ENV["DROPBOX_APP_MODE"])
